<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PZRecorder.Desktop</RootNamespace>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <Version>0.1.6</Version>
    <VersionSuffix>beta</VersionSuffix>
    <PublishReadyToRun>true</PublishReadyToRun>
    <ApplicationIcon>pz-recorder-icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="pz-recorder-icon.ico" />
  </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.3" />
        <PackageReference Include="Avalonia.Desktop" Version="12.0.3" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.3" />
        <PackageReference Include="Irihi.Ursa" Version="2.0.0" />
        <PackageReference Include="Irihi.Ursa.Themes.Semi" Version="2.0.0" />
        <PackageReference Include="Material.Icons.Avalonia" Version="3.0.2" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
        <PackageReference Include="Semi.Avalonia" Version="12.0.3" />
        <PackageReference Include="ClassicDiagnostics.Avalonia" Version="0.0.2-preview" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\PZRecord.Core\PZRecorder.Core.csproj" />
    </ItemGroup>
    <ItemGroup>
	    <ProjectReference Include="..\..\PZ.RxAvalonia\PZ.RxAvalonia\PZ.RxAvalonia.csproj" />
    </ItemGroup>
	
    <ItemGroup>
	    <ProjectReference Include="..\..\PZ.RxAvalonia\PZ.LocalizationGenerator\PZ.LocalizationGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	    <AdditionalFiles Include="Localization\languages.json" />
    </ItemGroup>
    <ItemGroup>
	    <None Update="Localization\*.json">
		    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    </None>
    </ItemGroup>
</Project>
